### ISSUE TITLE
No clear information on how to create shipnotices with items.

### ISSUE THREAD

**Issue by nikhgupta** [nikhgupta/whiplash_api#1]
Creating Shipnotice requires creating Shipnotice Items, which in turn, requires creating a shipnotice first. This should be made more clear in the API docs.

**Comment by ideaoforder** [comment]
This is a problem with the documentation:

1) You can currently create an empty shipnotice. We'll discuss internally and either update the doc, or add the requirement to the API.
2) When shipnotice_items within a shipnotice, you shouldn't specify a shipnotice_id. It works fine if you don't (same as with order_items). I'll update the doc to reflect this.

**Comment by nikhgupta** [comment]
Yeah, sorry, I was passing items as a hash, while I should have been passing them as an array. Seems like an oversight on my part. Sorry about that.

I have updated the tests, and the code to reflect this.

However, please note that, if the passed array is not valid (i.e. associated shipnotice_items, and order_items are not valid - e.g. if they are missing `quantity` field), the shipnotice/order is saved without spitting a validation error. IMO, if the associated child records could not be saved, it should throw an error. But, since, you said you will be working on validations later, I will close this for now.
