### ISSUE TITLE
Cannot filter listing of some resources using `since_id` parameter.

### ISSUE THREAD

**Issue by nikhgupta** [nikhgupta/whiplash_api#5]
`OrderItem` and `ShipnoticeItem` does not allow filtering the index listing using `since_id` parameter (as against to what the API docs say).

You can verify this by issuing the following CURL requests:

    curl -X GET -H "X-API-KEY: Hc2BHTn3bcrwyPooyYTP" "http://testing.whiplashmerch.com/api/order_items/72200.json"
    curl -X GET -H "X-API-KEY: Hc2BHTn3bcrwyPooyYTP" "http://testing.whiplashmerch.com/api/order_items/72201.json"
    curl -X GET -H "X-API-KEY: Hc2BHTn3bcrwyPooyYTP" "http://testing.whiplashmerch.com/api/order_items.json?order_id=47622&since_id=72200"

The first 2 requests assure that items exist after OrderItem ID: 72200, but the last request does not list these item. The same can be verified for `ShipnoticeItem`

**Comment by ideaoforder** [comment]
Fixed--deploying shortly.
