### ISSUE TITLE
Originator ID is not saved when creating Items

### ISSUE THREAD

**Issue by nikhgupta** [nikhgupta/whiplash_api#6]
### Creating item with a given Originator ID

**Request**

    curl -X POST -H "X-API-KEY: Hc2BHTn3bcrwyPooyYTP" "http://testing.whiplashmerch.com/api/items.json" -d 'sku=SOME-SKU-KEY&title=EEE&originator_id=123123123'

**Response**

    {"available":false,"created_at":"2015-10-01T07:24:27-04:00","currency":"USD","description":null,"exp_quantity":0,"height":null,"id":150182,"image_file_name":null,"image_originator_url":null,"image_updated_at":null,"is_bundle":false,"length":null,"media_mail":false,"packaging":false,"price":"0.0","quantity":0,"returnable":null,"scancode":null,"sku":null,"street_date":null,"title":null,"updated_at":"2015-10-01T07:24:27-04:00","vendor":null,"weight":null,"wholesale_cost":null,"width":null,"originators":[{"group_id":null,"original_id":null,"provider":"api"}]}

Note that, the response does not contain any `originator_id` field.

### When requesting item via the originator ID, we provided

**Request**

    curl -X GET -H "X-API-KEY: Hc2BHTn3bcrwyPooyYTP" "http://testing.whiplashmerch.com/api/items/originator/123123123.json"

**Response**

    null

As we can see, no items are return for the given originator ID.

**Comment by nikhgupta** [comment]
It seems that requesting items via Originator ID always returns `null`

**Comment by ideaoforder** [comment]
This does indeed seem to be a big. Your code should be correct, and I'll update this on our end, and post back soon.

**Comment by ideaoforder** [comment]
This is fixed and will be deployed shortly.
