### ISSUE TITLE
Wrong status name/code match for restricting updates on shipnotice items.

### ISSUE THREAD

**Issue by nikhgupta** [nikhgupta/whiplash_api#7]
Docs say that the restriction for status of shipnotices is:
**Note: You can only update shipnotice items for ship notices which are "processing" (status <= 100).**
![Screenshot](https://www.dropbox.com/s/rrkxotjf9tq9qy2/Screenshot%202015-10-01%2017.01.48.png?dl=1)

However, this status code and name does not match. At the moment, I have coded the gem so that it does not allow updating shipnotice items for shipnotices which are `processing`, i.e. (status <= **200**).
![Screenshot](https://www.dropbox.com/s/clw388ycdd78w23/Screenshot%202015-10-01%2017.03.39.png?dl=1)

**Comment by ideaoforder** [comment]
Your statuses are correct--the wording in the documentation is incorrect here. It should say:
Note: You can only create shipnotice items for ship notices which have yet to be received (status <= 100).

I've updated the doc and will deploy shortly.
